# Generated by Django 2.0.4 on 2018-05-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('channel_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('site_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.Site'),
        ),
    ]
