# Generated by Django 2.0.4 on 2018-05-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='icon',
            field=models.CharField(default='genericIcon.png', max_length=100),
        ),
    ]
