# Generated by Django 2.0.4 on 2018-05-23 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_desc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_thumb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userchannels',
            name='channels',
            field=models.ManyToManyField(to='mainApp.Channel'),
        ),
        migrations.AddField(
            model_name='userchannels',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
