# Generated by Django 2.0.4 on 2018-05-23 21:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0002_auto_20180523_0938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserChannels',
            new_name='UserChannel',
        ),
    ]
